/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase connection explicitly disabled
// System is running in local-only mode with mock data
export const projectId = "disabled"
export const publicAnonKey = "disabled"
