/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0beb8650 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/kdadxtrauodbqecrycfu/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.

// MOCK IMPLEMENTATION - No database connection
// All data is stored in-memory and will be lost on server restart

const memoryStore = new Map<string, any>();

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  memoryStore.set(key, value);
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  return memoryStore.get(key) || null;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  memoryStore.delete(key);
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  keys.forEach((k, i) => memoryStore.set(k, values[i]));
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  return keys.map(k => memoryStore.get(k) || null);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  keys.forEach(k => memoryStore.delete(k));
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const results: any[] = [];
  for (const [key, value] of memoryStore.entries()) {
    if (key.startsWith(prefix)) {
      results.push({ key, value });
    }
  }
  return results;
};